In [3]:
import numpy as np
grid_array = np.zeros(10000).reshape(100,100)
grid_array

In [162]:
input_array = """R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2"""

In [216]:
input_array = """U 1
D 1
R 1
L 2
D 2
U 1
R 2
D 2
U 1
R 1
L 1
D 2
R 2
U 2
L 1
D 1
U 1
L 1
D 2
U 1
D 1
L 1
U 2
R 1
L 1
R 1
L 1
U 2
L 2
U 2
L 1
U 2
D 1
U 2
D 1
L 2
U 1
D 1
U 2
R 2
D 2
R 1
D 2
L 1
U 1
L 2
D 2
L 2
R 1
U 1
L 2
D 1
U 1
R 2
L 2
D 1
R 1
L 1
R 2
U 1
R 2
D 1
U 1
L 2
D 1
R 2
D 1
U 2
R 1
D 1
R 2
U 1
L 2
D 2
U 2
R 2
L 1
D 2
R 1
D 1
U 2
D 2
L 2
R 2
L 2
D 1
R 2
D 2
L 1
U 1
D 1
L 2
U 1
R 1
D 1
U 2
D 1
L 2
D 2
R 2
L 2
R 2
U 2
L 1
R 1
L 1
D 2
R 2
U 1
R 1
D 2
R 1
L 1
R 3
L 3
D 1
R 2
D 2
U 1
D 1
R 2
D 1
L 3
U 3
L 1
U 3
L 1
D 2
R 3
L 2
R 1
U 3
R 2
D 3
L 2
D 1
R 1
L 2
U 3
D 2
U 3
R 1
L 2
D 2
R 2
U 3
D 1
L 2
D 1
R 1
D 3
U 1
R 1
D 3
L 1
D 3
U 1
L 3
R 1
D 1
L 1
U 3
R 2
D 1
U 3
L 1
D 1
L 3
R 2
D 1
L 2
U 1
L 2
U 1
R 1
L 2
D 2
R 2
L 1
R 2
U 3
D 3
R 3
L 3
R 1
L 2
D 1
U 1
R 2
D 2
R 2
D 1
U 1
D 3
U 2
R 3
U 3
R 3
U 2
R 1
L 2
D 1
R 2
U 1
R 2
D 2
R 3
L 2
R 1
D 2
L 3
U 3
R 1
D 1
L 1
R 1
D 1
R 3
U 2
D 3
U 3
R 2
D 4
L 3
U 3
L 2
R 4
U 1
D 4
R 1
U 3
L 1
D 4
L 3
R 1
D 3
R 1
L 2
R 3
L 3
R 1
D 1
R 4
L 3
R 2
L 1
R 4
U 3
D 2
R 3
D 1
R 1
L 3
R 4
L 4
U 3
L 4
R 4
U 2
D 2
R 3
L 4
U 4
L 3
D 4
R 1
U 1
L 3
U 2
L 2
R 4
D 3
R 2
U 2
R 4
D 1
R 4
U 3
D 3
R 1
U 4
L 1
R 3
D 3
U 3
L 4
U 4
D 4
L 3
D 4
U 4
R 2
D 2
U 3
D 2
U 4
D 2
L 2
D 2
R 2
D 4
L 2
U 3
D 1
U 1
R 2
U 3
L 4
U 1
R 3
U 3
D 3
U 4
D 2
R 3
L 4
R 4
D 3
U 2
R 4
D 1
R 4
U 3
R 4
L 4
D 3
L 3
D 3
U 4
R 4
D 2
R 2
D 1
R 4
L 3
D 5
L 1
D 3
L 4
R 2
U 2
L 3
R 3
U 5
D 1
U 1
R 5
D 5
L 1
R 4
L 4
R 4
D 4
R 4
D 3
L 4
U 2
L 2
D 5
U 5
L 1
R 2
D 2
R 2
D 2
U 2
R 5
U 2
R 2
U 4
L 2
U 3
R 5
U 2
R 2
D 2
R 4
U 5
D 5
R 3
U 4
L 5
U 3
D 2
R 5
U 3
L 5
U 2
R 1
L 1
R 3
L 2
R 5
L 5
U 1
R 2
L 2
D 1
R 3
L 5
D 5
U 4
R 4
L 3
R 2
D 2
L 3
D 3
R 4
U 2
R 5
D 1
R 1
D 3
L 4
R 3
D 4
L 4
D 5
R 3
L 1
U 1
D 5
U 2
L 5
D 3
U 4
D 5
U 1
R 2
D 5
L 2
U 1
D 4
R 3
D 2
U 5
L 4
R 2
D 4
U 4
R 4
D 5
R 2
L 2
R 5
U 5
R 6
D 6
U 4
L 6
D 4
R 1
L 1
D 6
R 4
L 1
U 4
D 3
U 3
D 2
U 6
R 1
U 4
L 6
R 5
D 4
R 6
D 3
R 1
L 5
D 3
R 3
D 6
R 6
D 2
R 6
D 1
L 1
R 5
U 1
D 5
L 6
R 4
U 3
L 2
D 4
U 1
D 2
R 4
L 6
D 6
U 5
D 2
R 4
L 4
U 3
D 1
R 3
L 1
D 1
L 1
D 4
L 6
U 1
L 2
D 6
R 1
L 5
U 6
L 1
D 2
L 4
R 3
D 3
R 6
L 6
R 5
U 2
R 4
D 4
U 5
D 1
U 5
R 4
L 3
R 6
U 4
L 3
R 3
L 3
U 6
D 3
L 3
R 1
L 5
R 1
D 2
L 6
R 6
D 5
R 6
U 3
R 3
L 5
D 6
R 2
D 3
R 4
D 1
R 4
D 5
U 4
D 1
L 2
D 7
L 7
D 3
U 4
R 1
D 4
R 3
L 1
U 2
L 1
D 1
R 4
D 7
U 5
R 5
U 1
L 3
R 3
L 4
R 2
U 3
R 3
U 2
L 4
R 3
U 2
L 1
D 4
U 7
L 5
D 7
L 2
D 6
R 1
D 4
R 2
D 7
L 5
D 4
R 3
L 1
U 5
D 1
U 7
L 3
U 5
L 3
U 2
R 2
L 7
U 1
R 5
U 3
L 2
D 7
L 2
R 5
D 3
L 7
D 7
U 6
R 6
L 5
U 2
D 7
L 5
R 5
D 4
R 5
L 7
D 1
U 7
R 2
L 3
R 6
L 3
R 6
L 2
R 5
L 2
R 2
D 7
U 4
R 7
U 2
D 5
R 4
U 4
R 1
L 4
R 1
U 1
L 1
U 7
R 1
L 7
D 3
L 6
U 6
L 6
U 2
D 7
L 7
R 1
D 5
U 4
L 5
U 7
L 6
U 3
R 5
L 5
D 5
L 8
R 8
L 5
D 2
L 2
R 7
D 6
L 2
U 7
R 6
D 3
U 2
L 4
D 5
R 4
D 6
R 4
D 3
R 3
L 5
R 5
L 7
R 6
D 5
U 7
R 1
U 1
R 1
L 6
R 6
L 3
U 2
D 6
U 4
R 5
U 4
R 4
D 4
U 1
L 1
D 4
U 4
L 3
R 1
U 1
R 8
U 8
D 2
R 7
U 8
R 8
U 3
D 5
U 2
R 3
D 5
R 4
L 6
U 3
L 4
D 6
U 2
L 2
D 5
U 1
R 2
D 7
L 4
R 6
L 4
D 5
L 3
R 7
U 5
D 3
L 5
D 8
L 8
U 7
D 8
R 6
U 5
R 2
U 5
D 5
U 7
R 3
L 6
D 1
U 6
L 3
R 5
U 5
R 2
L 4
U 8
D 8
L 7
R 1
U 8
L 4
U 1
D 1
R 3
D 8
L 4
U 7
L 5
D 2
U 6
D 1
L 5
R 1
U 6
R 1
D 7
U 3
L 7
R 9
D 5
L 5
U 5
R 7
U 3
L 7
R 3
U 3
L 3
U 5
D 8
R 4
L 1
U 7
D 3
L 7
U 6
D 4
U 7
D 6
R 9
L 8
R 4
L 7
U 7
R 7
L 4
U 1
L 5
D 5
L 6
U 6
D 6
R 7
L 3
R 9
U 2
R 6
D 8
L 3
R 6
L 7
D 2
U 9
D 2
L 6
D 9
R 6
D 1
U 7
L 8
U 5
L 9
R 7
D 9
L 7
D 9
U 6
R 5
L 7
D 8
R 4
L 4
U 5
D 3
R 2
D 3
R 1
L 3
R 8
D 6
U 3
D 3
U 4
R 6
U 2
R 3
U 5
R 7
D 1
U 9
D 4
U 5
D 9
R 4
U 2
D 5
U 2
R 8
U 9
L 9
R 3
L 6
D 4
L 2
D 6
U 8
R 3
L 2
U 1
L 3
R 4
L 1
D 1
U 5
R 9
D 10
U 4
L 1
U 10
D 2
L 9
R 10
U 8
L 2
U 10
R 2
L 2
D 10
R 10
U 9
R 6
L 9
D 2
U 6
R 8
U 9
L 7
R 5
U 2
D 8
R 4
D 5
U 7
D 2
R 2
U 2
D 1
R 1
D 9
L 10
R 3
D 5
R 8
U 5
R 1
U 3
L 3
U 7
R 10
U 4
D 7
U 3
L 3
R 6
U 6
D 7
R 3
U 2
D 9
R 7
D 1
L 3
D 6
L 4
D 5
L 3
U 7
R 2
D 8
U 1
L 8
R 4
D 8
L 2
D 6
L 9
R 9
U 1
R 10
L 3
U 8
D 9
R 8
D 8
U 2
D 8
L 4
U 2
D 3
L 4
R 6
L 4
D 4
L 6
U 1
R 1
D 4
L 7
R 8
U 8
L 9
D 5
R 1
U 2
D 8
U 8
L 10
D 9
L 1
R 4
U 10
R 7
D 1
U 9
L 5
R 3
U 2
R 3
L 3
U 7
R 8
L 10
R 4
D 5
U 3
L 10
R 4
U 7
L 8
U 4
L 2
R 10
D 11
L 10
D 10
L 11
R 9
D 9
R 5
L 5
D 10
R 11
U 1
R 11
U 5
R 9
U 8
L 1
R 7
U 7
D 5
R 5
L 6
R 8
L 10
R 9
U 6
D 9
L 7
U 7
L 9
R 5
D 8
R 8
U 6
R 11
L 7
D 9
R 6
L 5
R 9
U 8
L 3
U 9
L 2
R 9
L 8
R 1
L 9
R 4
L 2
U 1
R 8
L 8
D 2
L 8
R 3
D 8
L 1
R 11
L 3
R 8
D 3
L 10
R 10
D 5
R 9
D 4
U 3
L 6
R 2
U 10
D 7
U 8
L 4
D 7
U 4
D 7
L 7
R 9
L 1
R 6
D 10
U 4
D 11
U 7
R 4
U 10
L 7
R 9
D 11
U 11
R 6
U 9
L 5
D 10
R 9
L 10
R 1
D 4
R 2
L 4
U 5
L 4
D 11
U 8
R 12
L 10
D 7
R 4
U 9
R 5
D 8
U 9
L 3
R 3
L 3
U 11
L 3
D 9
U 2
R 3
D 2
L 4
U 7
R 10
U 2
D 10
U 7
L 1
U 10
L 1
D 10
U 12
R 5
L 4
R 10
U 6
D 2
R 6
U 11
D 1
U 2
L 1
D 12
R 2
U 3
D 7
U 2
L 9
D 7
R 3
U 5
R 10
U 7
D 5
L 6
U 11
D 11
L 1
D 10
R 1
L 5
U 10
L 11
R 10
U 2
D 7
U 10
L 10
U 11
D 7
R 6
D 3
L 11
U 4
R 8
U 6
D 2
U 8
R 3
L 7
R 5
U 8
D 3
L 12
U 12
D 10
U 7
L 10
R 8
D 8
U 11
R 3
U 10
R 6
D 2
U 3
D 12
L 5
U 11
R 9
L 4
U 6
R 11
D 1
L 6
U 5
D 12
L 9
U 6
L 13
D 7
L 10
U 13
L 11
U 6
D 11
U 11
L 6
U 5
D 2
L 10
D 5
R 6
D 13
R 9
D 4
L 2
R 11
U 13
L 3
R 10
U 2
L 13
U 10
D 4
L 2
R 5
L 8
U 4
D 1
U 3
D 10
U 13
D 2
L 11
R 7
L 5
R 7
D 10
R 13
D 6
R 11
L 11
R 9
L 11
D 13
U 3
L 6
U 7
L 12
D 1
R 7
L 7
U 1
D 6
R 6
U 11
D 2
L 10
R 5
L 6
R 6
U 2
R 11
D 10
U 9
L 4
U 7
R 3
U 9
R 11
U 6
L 5
D 1
U 13
L 11
D 1
L 9
R 8
D 4
U 4
L 1
R 1
L 6
R 11
D 10
R 3
U 2
L 3
R 1
U 10
R 3
U 2
L 1
D 5
U 11
R 11
U 11
L 3
U 3
R 3
L 3
U 10
L 14
U 14
D 6
L 11
R 6
U 8
L 12
R 11
U 1
L 9
D 11
U 8
D 6
R 2
L 12
R 11
D 2
R 3
D 5
L 4
U 2
D 12
U 12
L 5
R 2
U 13
R 1
L 2
D 13
R 8
L 14
U 14
L 9
R 10
U 5
D 3
U 12
D 13
R 2
D 8
R 10
L 6
U 12
D 12
R 6
D 12
R 13
L 5
R 10
D 10
L 8
R 5
L 2
U 6
D 2
U 9
L 1
D 8
L 7
D 10
L 6
R 1
L 6
D 14
U 6
R 10
D 4
R 2
D 13
U 9
R 11
U 8
R 4
L 6
R 14
L 10
U 14
D 12
R 3
D 12
L 8
U 13
R 4
L 3
R 14
U 11
D 13
L 8
U 1
D 2
L 11
R 7
D 5
R 11
L 1
D 13
L 7
R 4
U 7
D 13
L 2
R 8
D 1
R 13
L 9
D 4
R 12
D 10
U 12
D 7
U 5
L 3
U 9
D 12
R 8
D 13
R 8
D 5
L 14
U 7
D 4
R 14
D 14
R 2
D 5
L 2
D 13
U 7
L 8
R 10
D 9
U 11
D 3
U 3
D 2
L 9
D 2
U 10
D 7
L 5
R 10
D 15
R 1
U 7
D 10
U 14
R 12
L 14
U 7
R 5
U 2
L 3
R 13
U 12
D 1
L 15
D 10
R 6
U 9
R 13
U 3
D 13
U 1
R 4
L 1
R 8
U 14
L 1
R 10
L 12
D 15
R 6
U 13
L 2
R 13
D 9
U 3
R 4
D 11
U 6
D 9
L 12
R 1
D 11
R 11
U 11
R 5
D 2
L 3
R 12
L 8
R 1
L 12
U 9
L 3
U 7
D 2
U 9
L 10
D 1
U 7
R 9
D 11
L 8
D 4
R 2
U 12
D 12
U 6
R 5
D 2
R 1
D 5
U 6
L 10
D 13
R 5
U 12
L 4
U 8
L 12
U 13
L 1
D 4
L 9
U 3
D 15
U 3
D 15
R 1
D 10
U 11
R 7
U 3
R 13
D 3
U 3
R 9
L 12
D 1
U 5
D 1
R 9
D 5
U 15
D 9
L 10
R 6
L 4
D 6
R 5
U 15
R 9
U 16
D 3
R 9
U 11
D 16
U 7
L 1
U 8
R 12
L 1
R 6
D 9
U 11
L 5
D 5
R 14
D 1
L 3
R 8
L 3
D 8
U 11
R 12
U 10
L 3
U 10
L 1
R 9
L 8
D 2
R 5
U 3
R 2
D 9
R 3
D 12
U 5
D 13
L 7
R 15
L 9
U 9
D 7
R 6
D 9
L 7
R 11
L 10
R 9
U 13
L 11
U 10
L 2
D 13
L 13
R 15
D 6
R 15
U 10
R 12
D 8
U 16
L 6
R 9
U 12
D 4
R 6
U 7
L 11
U 12
L 5
R 11
L 16
R 3
U 5
L 14
R 12
L 13
D 1
L 9
D 8
L 6
R 6
D 15
L 14
R 17
U 12
D 12
R 15
D 2
L 11
R 9
U 1
R 5
U 17
R 3
D 16
U 6
D 16
R 8
L 10
U 13
L 9
D 12
R 1
U 4
R 8
D 11
R 15
D 15
L 4
D 10
L 6
U 15
L 1
R 1
D 16
U 7
R 13
D 6
L 14
R 15
U 5
R 4
U 7
R 6
U 17
L 12
U 6
L 5
R 16
L 10
D 6
R 7
U 15
R 3
U 3
D 16
L 8
R 13
L 1
U 2
R 5
D 17
U 10
L 16
U 2
L 3
D 2
R 10
L 6
R 9
U 3
L 5
U 2
D 2
U 4
D 10
R 9
U 8
L 9
D 16
R 3
U 3
L 15
D 11
R 1
U 11
R 11
L 12
R 11
D 17
R 4
D 14
R 10
U 4
R 5
D 12
U 16
D 3
R 1
L 15
U 11
R 1
D 3
L 9
D 3
L 7
U 5
R 12
U 10
R 16
U 12
D 9
R 10
U 2
R 3
D 15
R 14
L 11
D 18
R 12
D 6
U 5
L 8
U 7
D 15
R 8
D 15
L 7
R 18
L 5
R 8
L 10
D 12
R 14
U 2
L 7
R 17
U 4
L 1
U 10
D 18
L 3
U 5
D 12
L 4
R 14
U 5
L 18
U 18
D 14
R 11
U 6
L 4
R 13
D 18
U 18
R 18
U 7
D 4
L 17
D 2
U 11
L 13
D 13
L 14
U 2
R 6
L 3
D 1
L 8
U 3
R 5
D 7
L 2
D 4
U 1
R 1
U 8
D 2
U 3
R 2
D 15
U 1
R 9
L 2
R 2
U 3
L 16
U 16
R 16
L 11
U 9
D 10
R 18
U 14
D 7
R 16
D 7
R 7
L 3
U 17
R 18
U 10
L 15
R 3
U 6
R 1
U 1
R 14
D 12
R 10
L 7
U 11
D 15
U 9
L 11
U 13
D 16
R 8
U 5
L 5
U 10
R 5
L 15
D 6
L 16
D 4
L 19
R 8
U 18
L 7
D 15
R 5
U 9
L 2
U 17
L 2
U 17
R 2
L 13
D 19
L 16
U 6
D 13
R 15
D 13
U 7
L 7
R 8
D 10
L 13
D 4
L 5
U 8
L 12
R 13
U 5
R 9
U 16
L 5
D 14
L 4
R 8
U 4
L 10
R 17
D 12
L 14
U 18
D 3
U 9
R 12
L 3
R 15
L 17
D 4
R 6
L 5
R 8
D 19
L 15
D 5
L 8
R 7
L 13
D 3
L 17
D 12
R 5
L 9
U 3
L 17
D 10
R 17
L 12
R 16
L 7
D 4
R 18
U 10
R 19
L 19
R 1
U 10
D 2
L 8
U 9
L 15
D 1
R 15
U 10
R 18
U 16
R 17
L 16
D 9
R 18
U 16
L 9
R 14
U 7
L 8
D 15
L 7
U 10
D 18
L 13
R 1
D 8
R 14
L 12
U 2"""

In [178]:
input_array = """R 5
U 8
L 8
D 3
R 17
D 10
L 25
U 20"""

In [207]:
def move_tail(head_pos,tail_pos):
    diff = list(np.subtract(head_pos, tail_pos))
    #RIGHT
    if diff == [0,2]:
        tail_pos[1] += 1
    #LEFT
    elif diff == [0,-2]:
        tail_pos[1] -= 1
    #UP
    elif diff == [2,0]:
        tail_pos[0] += 1
    #DOWN
    elif diff == [-2,0]:
        tail_pos[0] -= 1
    #DIAG UL
    elif diff == [1,2] or diff == [2,1] or diff == [2,2]:
        tail_pos[0] += 1
        tail_pos[1] += 1
    elif diff == [-1,2] or diff == [-2,1] or diff == [-2,2]:
        tail_pos[0] -= 1
        tail_pos[1] += 1
    elif diff == [-1,-2] or diff == [-2,-1] or diff == [-2,-2]:
        tail_pos[0] -= 1
        tail_pos[1] -= 1
    elif diff == [1,-2] or diff == [2,-1] or diff == [2,-2]:
        tail_pos[0] += 1
        tail_pos[1] -= 1

    return tail_pos
def move_head(head_pos,command):
    if command[0] == 'U':
        head_pos[0] -= 1
    elif command[0] == 'D':
        head_pos[0] += 1
    elif command[0] == 'L':
        head_pos[1] -= 1
    elif command[0] == 'R':
        head_pos[1] += 1
    return head_pos

In [217]:
commands = [i.split(' ') for i in input_array.split('\n')]

In [248]:
commands = [i.split(' ') for i in input_array.split('\n')]
commands
single_commands = []
for command in commands:
    single_commands.extend(int(command[1]) * [command[0]])
single_commands

['U',
 'D',
 'R',
 'L',
 'L',
 'D',
 'D',
 'U',
 'R',
 'R',
 'D',
 'D',
 'U',
 'R',
 'L',
 'D',
 'D',
 'R',
 'R',
 'U',
 'U',
 'L',
 'D',
 'U',
 'L',
 'D',
 'D',
 'U',
 'D',
 'L',
 'U',
 'U',
 'R',
 'L',
 'R',
 'L',
 'U',
 'U',
 'L',
 'L',
 'U',
 'U',
 'L',
 'U',
 'U',
 'D',
 'U',
 'U',
 'D',
 'L',
 'L',
 'U',
 'D',
 'U',
 'U',
 'R',
 'R',
 'D',
 'D',
 'R',
 'D',
 'D',
 'L',
 'U',
 'L',
 'L',
 'D',
 'D',
 'L',
 'L',
 'R',
 'U',
 'L',
 'L',
 'D',
 'U',
 'R',
 'R',
 'L',
 'L',
 'D',
 'R',
 'L',
 'R',
 'R',
 'U',
 'R',
 'R',
 'D',
 'U',
 'L',
 'L',
 'D',
 'R',
 'R',
 'D',
 'U',
 'U',
 'R',
 'D',
 'R',
 'R',
 'U',
 'L',
 'L',
 'D',
 'D',
 'U',
 'U',
 'R',
 'R',
 'L',
 'D',
 'D',
 'R',
 'D',
 'U',
 'U',
 'D',
 'D',
 'L',
 'L',
 'R',
 'R',
 'L',
 'L',
 'D',
 'R',
 'R',
 'D',
 'D',
 'L',
 'U',
 'D',
 'L',
 'L',
 'U',
 'R',
 'D',
 'U',
 'U',
 'D',
 'L',
 'L',
 'D',
 'D',
 'R',
 'R',
 'L',
 'L',
 'R',
 'R',
 'U',
 'U',
 'L',
 'R',
 'L',
 'D',
 'D',
 'R',
 'R',
 'U',
 'R',
 'D',
 'D',
 'R',
 'L'

In [394]:
import pprint as pp
grid_size = 1000
np.set_printoptions(linewidth=300)
grid_array = np.zeros(grid_size**2).reshape(grid_size,grid_size)
grid_array

positions = [[int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)],
             [int(grid_size/2),int(grid_size/2)]
            ]

for command in commands:
    for step in range(int(command[1])):
#         print(command)
        head_position = move_head(positions[0],command)
        for knot_index in range(len(positions)-1):
#             print(knot_index)
            positions[knot_index+1] = move_tail(positions[knot_index],positions[knot_index+1])
#         pp.pprint(position_array(positions,grid_size))

        i,j = positions[-1]
        grid_array[i][j] = 1
print(grid_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [395]:
np.count_nonzero(grid_array)

2511

## Class-based option

In [477]:
from copy import deepcopy
class Knot:
    def __init__(self,position):
        self.position = position
        self.head_knot = None
        self.tail_knot = None

    def follow_head(self):
        if self.head_knot:
            self.position = move_tail(self.head_knot.position,self.position)
        if self.tail_knot:
            self.tail_knot.follow_head()
    def do_command(self,single_command):
        self.position = move_head_one(self.position, single_command)
        if self.tail_knot:
            self.tail_knot.follow_head()
    def create_tail(self):
        self.tail_knot = Knot(deepcopy(self.position))
        self.tail_knot.head_knot = self

def move_head_one(head_pos,single_command):
    if single_command == 'U':
        head_pos[0] -= 1
    elif single_command == 'D':
        head_pos[0] += 1
    elif single_command == 'L':
        head_pos[1] -= 1
    elif single_command == 'R':
        head_pos[1] += 1
    return head_pos        

In [478]:
commands = [i.split(' ') for i in input_array.split('\n')]
commands
single_commands = []
for command in commands:
    single_commands.extend(int(command[1]) * [command[0]])


In [479]:
np.set_printoptions(linewidth=300)
num_knots = 10
grid_size = 1000
default_start = [int(grid_size/2),int(grid_size/2)]
grid_array = np.zeros(grid_size**2).reshape(grid_size,grid_size)
np.count_nonzero(grid_array)

0

In [480]:
head_knot = Knot(default_start)

# Create a new tail for the knot
head_knot.create_tail()
current_tail = head_knot.tail_knot
for i in range(8):
    
    # Create a new tail for the current tail
    current_tail.create_tail()
    
    # Set the current tail to the new tail
    current_tail = current_tail.tail_knot
final_tail_knot = current_tail

In [481]:
for command in single_commands:
    head_knot.do_command(command)
    i,j = final_tail_knot.position
    grid_array[i][j] = 1
print(grid_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [482]:
np.count_nonzero(grid_array)

2511

In [483]:
def position_array(positions, grid_size):
    current_position =  np.zeros(grid_size**2).reshape(grid_size,grid_size)
    for i in range(len(positions)):
        r,c = positions[i]
        current_position[r][c] = i+1
    return current_position